# Generated by Django 6.0.1 on 2026-02-01 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('raw_motion', 'Raw Motion'), ('raw_biometric', 'Raw Biometric'), ('raw_air', 'Raw Air'), ('raw_gnss', 'Raw Gnss'), ('processed_motion', 'Processed Motion'), ('processed_biometric', 'Processed Biometric'), ('processed_air', 'Processed Air')], max_length=32)),
                ('timestamp', models.DateTimeField(help_text='Epoch o timestamp del dato')),
                ('payload', models.JSONField(help_text='Dati decodificati dalla caratteristica BLE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'data_type', 'timestamp'], name='measurement_device__33b4c3_idx')],
            },
        ),
    ]
