# Generated by Django 6.0.1 on 2026-02-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='ID univoco del dispositivo (BLE MAC o UUID)', max_length=64, unique=True)),
                ('name', models.CharField(blank=True, help_text="Nome leggibile assegnato dall'utente", max_length=128)),
                ('model', models.CharField(blank=True, help_text='Modello hardware', max_length=64)),
                ('firmware_version', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
